Feature/ticket box
syg4806/SmartGate pull request #12
Opened 2020-06-12 12:39 UTC by seyoung5744

UI 수정 완료했습니다. 
#11 이슈도 해결해서 포함했습니다.

2020-06-13 08:33 UTC, syg4806 requested changes

2020-06-13 08:33 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
>    val now = Calendar.getInstance()
클래스 멤버 변수는 접근지정자 신경써주세요. 다른곳에서 접근할 필요가 없으면 private으로 해주세요

2020-06-13 08:33 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
> +            Toast.makeText(baseContext, "인식 가능한 지문이 등록되어 있지 않습니다.", Toast.LENGTH_LONG).show()
Toast메세지는 extension에 만ㄹ어 둔 걸로 사용해주세요

2020-06-13 08:33 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
> +              .show()*/
사용하지 않거나 불필요한 주석은 풀리퀘를 쏘기전에 제거해주세요

2020-06-13 08:33 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
> +            Toast.makeText(baseContext, "인식 가능한 지문이 등록되어 있지 않습니다.", Toast.LENGTH_LONG).show()
밑에도 toast 사용하는 곳들 바꿔주세요

2020-06-13 08:33 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
> +        Logg.d("ssmm11 App can authenticate using biometrics.")
Log에서 본인만 알아 볼 수 있는 TAG용 스트링은 빼주세요

2020-06-13 08:33 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
>      }
리스너의 형태 제거하고 apply등 같은 scope 형태의 extension으로 변경해주세요

2020-06-13 08:33 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
> +    setMyTicketCount = (ticketCountSpinner.selectedItem as String).toInt()
setMyTicketCount 이친구가 클래스 멤버 변수일 필요가 있나요?

2020-06-13 08:33 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
>        ticketCountSpinner.adapter = arrayAdapter
한 arrayAdapter  변수에 서로 다른 두개의 ArrayAdapter를 넣는 건 좋지 않은 것 같네요.
굳이 저 변수 없어도 될 것 같아요. 바로 Spinner에 넣어 줘도 될 것 같습니다

2020-06-13 08:33 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/placelist/PlaceListActivity.kt
> +        bookingRecyclerView.layoutManager = LinearLayoutManager(activity)
activity변수로 갖을 필요가 없을  것 같아요 바로 this로 넣어주거나, this@PlaceListActivity 로 넣어줄 수 있을 것 같아요

2020-06-13 08:33 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/placelist/PlaceListActivity.kt
>        R.id.searchButton -> {
해당 버튼의 기능은 어디있을까용

2020-06-13 08:33 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/placelist/PlaceListRecyclerViewAdapter.kt
> +  var context: Context? = null // 부모 context
해당 context는 생성자 통해서 얻는 방법이 좋을 것 같아요

2020-06-13 08:37 UTC, seyoung5744 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
> +        Logg.d("ssmm11 App can authenticate using biometrics.")
정빈님 혼날래요??

2020-06-13 08:37 UTC, seyoung5744 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
> +        Logg.d("ssmm11 App can authenticate using biometrics.")
정빈님 혼날래요??

2020-06-14 05:01 UTC, syg4806 requested changes

2020-06-14 05:01 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/myticket/MyTicketActivity.kt
> -class MyTicketActivity : AppCompatActivity(), CoroutineScope by MainScope() {
CoroutineScope by MainScope() 이거 왜 빼시고 MainScope를 직접호출하시나유?

2020-06-14 05:01 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/myticket/MyTicketRecyclerAdapter.kt
>    var context: Context? = null
adapter에 필요한 context는 생성자 통해서 받을 수 있을거에요

2020-06-14 05:01 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/myticket/MyTicketRecyclerAdapter.kt
>      var imgUri: Uri? = null
멤버 변수는 private 함수도 private 신경써주세요

2020-06-14 05:01 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/myticket/MyTicketRecyclerAdapter.kt
> +       nextIntent.putExtra("certificateNo", ownedTicket.certificateNo) //nickname 정보 인텐트로 넘김
intent에 name으로 넘겨지는 스트링은 상수로 사용해주세요

2020-06-14 05:01 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/send/FriendListRecyclerViewAdapter.kt
> +    Logg.d("나와라~")
불필요한 로그 제거!

2020-06-14 05:06 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
> +        Logg.d("ssmm11 App can authenticate using biometrics.")
수정했습니다.. ㅎ

2020-06-14 05:09 UTC, seyoung5744 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
> +    setMyTicketCount = (ticketCountSpinner.selectedItem as String).toInt()
` val setTicketListener = object : SetTicketListener {  

    override fun setMyTicket() {
      setMyTicketCount--
      if (setMyTicketCount == 0) {
        startActivity(Intent(this@BookingActivity, MyTicketActivity::class.java))
        finish()
      }
    }
  }`

위 코드처럼 네트워크 리스너에서 사용하려고 멤버 변수로 선언한거 같네요
@김정빈

2020-06-14 05:12 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
> +    setMyTicketCount = (ticketCountSpinner.selectedItem as String).toInt()
네트워크 리스너에서 사용하려고 달았는데 리스너 제거 작업중에 필요가 없어진다면 수정하겠습니다

2020-06-14 05:13 UTC, seyoung5744 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
>        ticketCountSpinner.adapter = arrayAdapter
![image](https://user-images.githubusercontent.com/53173850/84585286-3c8de800-ae49-11ea-97a1-9d202e0e424a.png)

다음처럼 수정 완료

2020-06-14 05:14 UTC, seyoung5744 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
>      }
@JungBinKim0913 
브랜치파서 작업할 예정

2020-06-14 05:16 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/placelist/PlaceListActivity.kt
> +        bookingRecyclerView.layoutManager = LinearLayoutManager(activity)
수정 완료 했습니다.

2020-06-14 05:16 UTC, seyoung5744 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
>    val now = Calendar.getInstance()
nextIntent = Intent(this@BookingActivity, MyTicketActivity::class.java)
Intent 사용할 때 this@BookingActivity 처럼 해두면 따로 할당할 필요 없음

now는 버튼 클릭할때만 필요해서 onClick에 선언

2020-06-14 05:17 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/placelist/PlaceListActivity.kt
>        R.id.searchButton -> {
아직 서치 버튼 구현이 안되어있어서 TODO로 해두겠습니다.

2020-06-14 05:22 UTC, seyoung5744 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/myticket/MyTicketActivity.kt
> -class MyTicketActivity : AppCompatActivity(), CoroutineScope by MainScope() {
activity 는 BaseActivity에  MainScope() 달아서 상속할게요.
그 외에 꺼는 직접 상속

2020-06-14 08:27 UTC, syg4806 requested changes

2020-06-14 08:27 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/LoginActivity.kt
>    lateinit var mContext: Context
사용하지 않는 변수인 것 같아요

2020-06-14 08:27 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
>    var setMyTicketCount = 0
private

2020-06-14 08:27 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/mypage/usedticketlookup/UsedTicketActivity.kt
>          usedTicketEmptyTicketView.visibility = View.VISIBLE
View의 visible 변경하는 것도extension으로 만들어놨어요.

2020-06-14 08:27 UTC, merged