카드 등록 및 지문 인식 결제, 지문 없을 때 결제 비밀번호로 결제 구현
syg4806/SmartGate pull request #13
Opened 2020-06-12 14:57 UTC by JungBinKim0913

받아주세영 ㅎㅎ

2020-06-14 15:38 UTC, syg4806 requested changes
전반적으로 접근지정자, BaseActivity() 상속, Logg 사용 신경써주세요
extension도 활용할 수 있으면 활용해주세요

2020-06-14 15:38 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/network/FBUsersRepository.kt
> +    db.collection("users").document(userInfo.uid!!).set(userInfo)
"users" -> 상수로

2020-06-14 15:38 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/LoginActivity.kt
> +      md = MessageDigest.getInstance("SHA")
```
val md = MessageDigest.getInstance("SHA")
```
로 수정 될 것 같네요

2020-06-14 15:38 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/LoginActivity.kt
> +            Log.d("","KAKAO_SESSION", "로그인 실패", exception)
Logg 로 변경해주세요

2020-06-14 15:38 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/PaymentKeySettingActivity.kt
> +  var passwordConfirmation = false
private

2020-06-14 15:38 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/PaymentKeySettingActivity.kt
> +  private fun check(mode: Boolean) {
이미지 뷰를 배열에 넣어서 인덱스로 접근해서 변경하고 하면 함수화 할 수 있지않을까요?
코드가 반복된다 싶으면 함수화 생각해보면 좋을 것 같아요

2020-06-14 15:38 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/PaymentKeySettingActivity.kt
> +      // TODO 비밀번호 확인 만들기
todo 해결한 거 아닌가요?

2020-06-14 15:38 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/PaymentKeySettingActivity.kt
> +class PaymentKeySettingActivity : AppCompatActivity(), View.OnClickListener {
코드 전반적으로 MVVM을 사용하면 코드가 훨씬 간결해질 것 같다 생각드네요

2020-06-14 15:38 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/PaymentKeySettingActivity.kt
> +class PaymentKeySettingActivity : AppCompatActivity(), View.OnClickListener {
MVVM은 시간이 되면 적용해주세요

2020-06-14 15:38 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
> +      if (resultCode == 100) {
한번에 가능할 것 같네요
```
if(requestCode==0 &&resultCode==100)
```

2020-06-14 15:38 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
> +      // TODO 회원가입 시 , 묻기 |||| 지문인식 결제 할 때 검사해서 하기
todo 체크해주세요

2020-06-14 15:38 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/PaymentKeyBookingActivity.kt
> +class PaymentKeyBookingActivity : AppCompatActivity(), View.OnClickListener {
이전에 있던 비밀번호 입력하던 액티비티랑 구조가 너무 비슷한데, 상속개념을 적용해보는건 어떨까요

2020-06-14 15:38 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/mypage/cardmanagement/CardManagementActivity.kt
> +        if (it != null) {
?.let 과 ?:로 변경가능할듯해요

2020-06-14 15:38 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/mypage/cardmanagement/CardManagementActivity.kt
> +          cardDeleteButton.visibility = View.VISIBLE
이런 단순한 뷰 속성 변화는 extension으로 만들어서 사용한다고 합니다

2020-06-14 15:45 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/mypage/cardmanagement/CardManagementActivity.kt
> +        if (it != null) {
👍

2020-06-14 15:47 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/mypage/cardmanagement/CardManagementActivity.kt
> +          cardDeleteButton.visibility = View.VISIBLE
해당 내용 전체 project 단위에서 View.extension 사용하도록 수정하였습니다.

2020-06-14 15:48 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
> +      if (resultCode == 100) {
👍

2020-06-14 15:53 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/PaymentKeySettingActivity.kt
> +  private fun check(mode: Boolean) {
👍

2020-06-20 08:03 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/PaymentKeyBookingActivity.kt
> +class PaymentKeyBookingActivity : AppCompatActivity(), View.OnClickListener {
상속 개념을 적용하여 수정완료 했습니다.

2020-06-20 08:04 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/PaymentKeySettingActivity.kt
> +  var passwordConfirmation = false
상속을 적용하면서, 다른 액티비티에서 호출하는 부분 떄문에 private로 사용하지 못합니다.

2020-06-20 08:06 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/LoginActivity.kt
> +            Log.d("","KAKAO_SESSION", "로그인 실패", exception)
👍

2020-06-20 08:06 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/LoginActivity.kt
> +      md = MessageDigest.getInstance("SHA")
👍

2020-06-20 08:07 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/network/FBUsersRepository.kt
> +    db.collection("users").document(userInfo.uid!!).set(userInfo)
BaseFB 를 파이어 베이스 작업을 위한 부모로 두고 다른 활용하는 부분에서 상속을 받아서 사용하려 합니다.
시간이 비교적 걸리는 작업으로 생각되어 새로 브랜치를 만들어서 작업할 예정입니다.

2020-06-20 08:08 UTC, JungBinKim0913 commented
@syg4806 코드 리뷰 부분 수정 완료하였습니다. 확인 한 번 더 부탁드리겠습니다.

2020-06-20 08:37 UTC, syg4806 reviewed
1. 상속부분 다시
2. 카드 레이아웃 다시

2020-06-20 08:37 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/network/FBPaymentKeyRepository.kt
> +  }
어떤 기능이쥬

2020-06-20 08:37 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/network/FBUsersRepository.kt
> +    }
```
return db.collection("users").document(SharedPref.autoLoginKey).collection("card").get()
        .await()
        .documents
        .first().toObject(CardData::class.java)
바로 이렇게 해도 될 것 같은데요??

```

2020-06-20 08:37 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/LoginActivity.kt
>    lateinit var mContext: Context
빼주셔요

2020-06-20 08:37 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/LoginActivity.kt
> +      TODO("VERSION.SDK_INT < P")
pi 이하일 경우는?

2020-06-20 08:37 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/LoginActivity.kt
> +          intent.putExtra("email", result.kakaoAccount.email)
"email" => 상수로!

2020-06-20 08:37 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
>            "결제 동의를 클릭해주세요".show()
이런 케이스를 거르는 경우는 
if (!bookingCheckBox.isChecked) {
"결제 동의를 클릭해주세요".show()
return
}
if (SharedPref.useFingerPrint) { // 지문 인식 기능을 check 한 경우 지문인식으로 결제
            showBiometricPrompt()
          } else { // 지문 인식 기능이 off 인 경우 결제 비밀번호로 결제
            val intent = Intent(baseContext, PaymentKeyBookingActivity::class.java)
            startActivityForResult(intent, 0)
          }
이렇게하면 if의 뎁스를 줄일 수 있겠죠

2020-06-20 08:37 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
>      setMyTicketCount = (ticketCountSpinner.selectedItem as String).toInt()
변수명이 좋지 않은 것 같아요

2020-06-20 08:37 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/BookingActivity.kt
>      setMyTicketCount = (ticketCountSpinner.selectedItem as String).toInt()
ticketCount로 하는게 오히려 가독성이 좋을듯합니당

2020-06-20 08:37 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/mypage/cardmanagement/CardAddActivity.kt
> +class CardAddActivity : AppCompatActivity(), View.OnClickListener, CoroutineScope by MainScope() {
BaseActivity!!

2020-06-20 08:37 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/mypage/cardmanagement/CardAddActivity.kt
> +        }
여기서 return을 콜해주면 아래 else의 뎁스를 줄일수있을듯해요

2020-06-20 08:37 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/mypage/cardmanagement/CardManagementActivity.kt
> +class CardManagementActivity : AppCompatActivity(), View.OnClickListener,
B.A.S.E.A.C.T.I.V.I.T.Y

2020-06-20 08:37 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/mypage/cardmanagement/CardManagementActivity.kt
> +  lateinit var nextIntent: Intent
intent가 멤버변수로 있을 필요가 있을까요?

2020-06-20 08:37 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/mypage/cardmanagement/CardManagementActivity.kt
> +    nextIntent = Intent(this, CardAddActivity::class.java)
인텐트는 넘겨지는 시점에 바로 선언해서 사용해주는게 좋을 것 같네요

2020-06-20 08:46 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/PaymentKeySettingActivity.kt
> +  lateinit var imageViewList : ArrayList<ImageView>
private 아니면 protected로 지정 가능할 듯해요

2020-06-20 08:46 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/PaymentKeySettingActivity.kt
> +    clickSetting(v)
이 친구가 함수로 빠진 이유는?

2020-06-20 08:46 UTC, syg4806 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/PaymentKeyBookingActivity.kt
> +    clickSetting(v)
PaymentKeySettingActivity 랑 같은 작업을 하는데 override가 필요한 이유는?

2020-06-20 08:58 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/booking/PaymentKeyBookingActivity.kt
> +    clickSetting(v)
아까 수정한거와 같이 수정

2020-06-20 08:58 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/PaymentKeySettingActivity.kt
> +    clickSetting(v)
아래 문제를 해결하면서 같이 뺐습니다

2020-06-20 09:07 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/PaymentKeySettingActivity.kt
> +  lateinit var imageViewList : ArrayList<ImageView>
booking 에서 해당 뷰를 상속하기 때문에 접근을 하는 경우는 protected, 안하는 경우는 private로 수정하였습니다.

2020-06-20 09:08 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/main/mypage/cardmanagement/CardManagementActivity.kt
> +    nextIntent = Intent(this, CardAddActivity::class.java)
수정하였습니다.

2020-06-20 09:17 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/LoginActivity.kt
> +          intent.putExtra("email", result.kakaoAccount.email)
상수 작업 BaseFB 작업 떄 같이 진행하겠습니다.

2020-06-20 09:27 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/ui/login/LoginActivity.kt
> +      TODO("VERSION.SDK_INT < P")
해당 함수는 kakao Developer 등록을 위해 남겨둔 코드입니다. 주석 처리 해놓았습니다.

2020-06-20 11:26 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/network/FBPaymentKeyRepository.kt
> +  }
수정 중에 사용하지 않는 코드가 되었네요 삭제 했습니다.

2020-06-20 11:41 UTC, JungBinKim0913 commented on SmartGateAndroid/app/src/main/java/com/chambit/smartgate/network/FBUsersRepository.kt
> +    }
저 방식이면 documents 는 null은 아니고 비어있는 상태 (empty) 이기 때문에 first()가 접근을 시도하지만 비어있어서 Collection이 오류가 생긴 문제가 있었습니다. 코드는 같이 줄여서
![image](https://user-images.githubusercontent.com/56395829/85200944-69a13580-b336-11ea-900f-fbf83137c97d.png)
위 모양으로 변환은 적용했습니다.

2020-06-20 11:55 UTC, syg4806 approved these changes

2020-06-20 11:55 UTC, merged